import {
  LayoutDashboard,
  Users,
  HeartPulse,
  Stethoscope,
  CreditCard,
  FlaskConical,
  ScanLine,
  Pill,
  BedDouble,
  ShoppingBag,
  Package,
  Receipt,
  BookOpen,
  Building2,
  UserCog,
  MessageSquare,
  FileBarChart,
  Shield,
  Activity,
  UserPlus,
  Search,
  ClipboardList,
  ArrowRightLeft,
  Clock,
  Thermometer,
  Syringe,
  FileText,
  Clipboard,
  ListOrdered,
  History,
  TestTube,
  Printer,
  BarChart3,
  Image,
  CheckCircle,
  DollarSign,
  Wallet,
  CreditCard as CardIcon,
  FileSpreadsheet,
  PlusCircle,
  ShoppingCart,
  Truck,
  AlertCircle,
  BarChart,
  Layers,
  ArrowDownUp,
  ClipboardCheck,
  SendHorizonal,
  BadgeDollarSign,
  Calculator,
  Landmark,
  ArrowLeftRight,
  TrendingUp,
  Wrench,
  CalendarDays,
  UserCheck,
  Banknote,
  Mail,
  Bell,
  Send,
  Inbox,
  PieChart,
  Table,
  Download,
  Settings,
  Lock,
  UsersRound,
  ScrollText,
  Ambulance,
  Scissors,
  Droplets,
  CalendarPlus,
  Video,
  Cross,
  ShieldCheck,
  Cpu,
  Server,
  Wifi,
  UtensilsCrossed,
  FileCheck,
  Phone,
  MapPin,
  Timer,
  Bed,
  Zap,
  Heart,
  Eye,
  Workflow,
  FolderOpen,
  GitBranch,
  Scale,
  CircleDot,
  Beaker,
  Gauge,
  Crown,
  Power,
  AlertTriangle,
  Ticket,
  type LucideIcon,
} from "lucide-react";

export interface SubModule {
  title: string;
  url: string;
  icon: LucideIcon;
}

export interface Module {
  key: string;
  label: string;
  icon: LucideIcon;
  color: string;
  basePath: string;
  submodules: SubModule[];
}

const baseModules: Module[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    color: "192 70% 38%",
    basePath: "/",
    submodules: [
      { title: "Overview", url: "/", icon: LayoutDashboard },
      { title: "Analytics", url: "/dashboard/analytics", icon: BarChart3 },
      { title: "Recent Activity", url: "/dashboard/activity", icon: Clock },
    ],
  },
  {
    key: "appointments",
    label: "Appointments / OPD",
    icon: CalendarPlus,
    color: "220 65% 50%",
    basePath: "/appointments",
    submodules: [
      { title: "Today's Schedule", url: "/appointments", icon: CalendarDays },
      { title: "Book Appointment", url: "/appointments/book", icon: PlusCircle },
      { title: "Doctor Schedule", url: "/appointments/doctor-schedule", icon: Stethoscope },
      { title: "Walk-in Registration", url: "/appointments/walkin", icon: UserPlus },
      { title: "Appointment History", url: "/appointments/history", icon: History },
    ],
  },
  {
    key: "patients",
    label: "Patient Registry",
    icon: Users,
    color: "210 60% 45%",
    basePath: "/patients",
    submodules: [
      { title: "All Patients", url: "/patients", icon: Users },
      { title: "New Registration", url: "/patients/register", icon: UserPlus },
      { title: "Search", url: "/patients/search", icon: Search },
      { title: "Queue Management", url: "/patients/queue", icon: ClipboardList },
      { title: "Transfers", url: "/patients/transfers", icon: ArrowRightLeft },
    ],
  },
  {
    key: "emergency",
    label: "Emergency / A&E",
    icon: Ambulance,
    color: "0 80% 50%",
    basePath: "/emergency",
    submodules: [
      { title: "Emergency Dashboard", url: "/emergency", icon: Zap },
      { title: "Triage Assessment", url: "/emergency/triage", icon: HeartPulse },
      { title: "Trauma Cases", url: "/emergency/trauma", icon: Ambulance },
      { title: "Resuscitation", url: "/emergency/resuscitation", icon: Heart },
      { title: "Emergency Billing", url: "/emergency/billing", icon: CreditCard },
    ],
  },
  {
    key: "triage",
    label: "Triage & Nursing",
    icon: HeartPulse,
    color: "0 65% 55%",
    basePath: "/triage",
    submodules: [
      { title: "Triage Queue", url: "/triage", icon: ClipboardList },
      { title: "Vitals Entry", url: "/triage/vitals", icon: Thermometer },
      { title: "Nursing Procedures", url: "/triage/procedures", icon: Syringe },
      { title: "Care Notes", url: "/triage/notes", icon: FileText },
      { title: "Vitals History", url: "/triage/history", icon: History },
    ],
  },
  {
    key: "doctor",
    label: "Doctor's Module",
    icon: Stethoscope,
    color: "152 60% 40%",
    basePath: "/doctor",
    submodules: [
      { title: "OPD", url: "/doctor", icon: ListOrdered },
      { title: "IPD", url: "/doctor/ipd", icon: Clipboard },
    ],
  },
  {
    key: "billing",
    label: "Cashier & Billing",
    icon: CreditCard,
    color: "38 92% 50%",
    basePath: "/billing",
    submodules: [
      { title: "Billing Queue", url: "/billing", icon: ListOrdered },
      { title: "New Invoice", url: "/billing/invoice", icon: PlusCircle },
      { title: "Payments", url: "/billing/payments", icon: Wallet },
      { title: "Receipts", url: "/billing/receipts", icon: Receipt },
      { title: "Insurance Claims", url: "/billing/claims", icon: FileSpreadsheet },
    ],
  },
  {
    key: "insurance",
    label: "Insurance & TPA",
    icon: ShieldCheck,
    color: "200 55% 48%",
    basePath: "/insurance",
    submodules: [
      { title: "Pre-Authorization", url: "/insurance", icon: FileCheck },
      { title: "Claim Submission", url: "/insurance/claims", icon: SendHorizonal },
      { title: "Claim Tracking", url: "/insurance/tracking", icon: Eye },
      { title: "TPA Management", url: "/insurance/tpa", icon: Building2 },
      { title: "Rate Contracts", url: "/insurance/rates", icon: BadgeDollarSign },
    ],
  },
  {
    key: "laboratory",
    label: "Laboratory",
    icon: FlaskConical,
    color: "270 50% 55%",
    basePath: "/laboratory",
    submodules: [
      { title: "Test Queue", url: "/laboratory", icon: ListOrdered },
      { title: "Sample Collection", url: "/laboratory/samples", icon: TestTube },
      { title: "Results Entry", url: "/laboratory/results", icon: Clipboard },
      { title: "Print Reports", url: "/laboratory/reports", icon: Printer },
      { title: "Test Templates", url: "/laboratory/templates", icon: FileText },
    ],
  },
  {
    key: "radiology",
    label: "Radiology",
    icon: ScanLine,
    color: "210 80% 55%",
    basePath: "/radiology",
    submodules: [
      { title: "Exam Queue", url: "/radiology", icon: ListOrdered },
      { title: "Imaging", url: "/radiology/imaging", icon: Image },
      { title: "Reports", url: "/radiology/reports", icon: FileText },
      { title: "Validation", url: "/radiology/validation", icon: CheckCircle },
    ],
  },
  {
    key: "pharmacy",
    label: "Pharmacy",
    icon: Pill,
    color: "152 55% 45%",
    basePath: "/pharmacy",
    submodules: [
      { title: "Dispensing", url: "/pharmacy", icon: Pill },
      { title: "OTC Sales", url: "/pharmacy/otc", icon: ShoppingCart },
      { title: "Stock Control", url: "/pharmacy/stock", icon: Package },
      { title: "Expiry Tracking", url: "/pharmacy/expiry", icon: AlertCircle },
      { title: "Reports", url: "/pharmacy/reports", icon: BarChart },
    ],
  },
  {
    key: "inpatient",
    label: "In-Patient",
    icon: BedDouble,
    color: "192 55% 45%",
    basePath: "/inpatient",
    submodules: [
      { title: "Ward Overview", url: "/inpatient", icon: BedDouble },
      { title: "Admissions", url: "/inpatient/admissions", icon: UserPlus },
      { title: "Bed Management", url: "/inpatient/beds", icon: Layers },
      { title: "Discharges", url: "/inpatient/discharges", icon: CheckCircle },
      { title: "Transfers", url: "/inpatient/transfers", icon: ArrowDownUp },
    ],
  },
  {
    key: "theatre",
    label: "Operation Theatre",
    icon: Scissors,
    color: "340 60% 50%",
    basePath: "/theatre",
    submodules: [
      { title: "OT Schedule", url: "/theatre", icon: CalendarDays },
      { title: "Surgery Booking", url: "/theatre/booking", icon: PlusCircle },
      { title: "Pre-Op Assessment", url: "/theatre/preop", icon: ClipboardCheck },
      { title: "OT Notes", url: "/theatre/notes", icon: FileText },
      { title: "Post-Op Care", url: "/theatre/postop", icon: HeartPulse },
      { title: "OT Utilization", url: "/theatre/utilization", icon: BarChart3 },
    ],
  },
  {
    key: "blood-bank",
    label: "Blood Bank",
    icon: Droplets,
    color: "0 70% 45%",
    basePath: "/blood-bank",
    submodules: [
      { title: "Blood Inventory", url: "/blood-bank", icon: Package },
      { title: "Donor Registration", url: "/blood-bank/donors", icon: UserPlus },
      { title: "Blood Collection", url: "/blood-bank/collection", icon: Droplets },
      { title: "Cross Matching", url: "/blood-bank/crossmatch", icon: GitBranch },
      { title: "Blood Issue", url: "/blood-bank/issue", icon: SendHorizonal },
    ],
  },
  {
    key: "cssd",
    label: "CSSD",
    icon: ShieldCheck,
    color: "170 50% 42%",
    basePath: "/cssd",
    submodules: [
      { title: "Sterilization Queue", url: "/cssd", icon: ListOrdered },
      { title: "Instrument Tracking", url: "/cssd/instruments", icon: Wrench },
      { title: "Cycle Monitoring", url: "/cssd/cycles", icon: Workflow },
      { title: "Quality Control", url: "/cssd/quality", icon: CheckCircle },
    ],
  },
  {
    key: "nutrition",
    label: "Nutrition & Diet",
    icon: UtensilsCrossed,
    color: "80 55% 45%",
    basePath: "/nutrition",
    submodules: [
      { title: "Diet Plans", url: "/nutrition", icon: ClipboardList },
      { title: "Meal Orders", url: "/nutrition/meals", icon: UtensilsCrossed },
      { title: "Kitchen Management", url: "/nutrition/kitchen", icon: Gauge },
      { title: "Dietary Assessment", url: "/nutrition/assessment", icon: FileCheck },
    ],
  },
  {
    key: "telemedicine",
    label: "Telemedicine",
    icon: Video,
    color: "250 55% 55%",
    basePath: "/telemedicine",
    submodules: [
      { title: "Virtual Consultations", url: "/telemedicine", icon: Video },
      { title: "Schedule Session", url: "/telemedicine/schedule", icon: CalendarPlus },
      { title: "E-Prescriptions", url: "/telemedicine/prescriptions", icon: FileText },
      { title: "Patient Portal", url: "/telemedicine/portal", icon: Users },
    ],
  },
  {
    key: "mortuary",
    label: "Mortuary",
    icon: Cross,
    color: "210 15% 40%",
    basePath: "/mortuary",
    submodules: [
      { title: "Body Register", url: "/mortuary", icon: FolderOpen },
      { title: "Admission", url: "/mortuary/admission", icon: PlusCircle },
      { title: "Release", url: "/mortuary/release", icon: FileCheck },
      { title: "Death Certificates", url: "/mortuary/certificates", icon: FileText },
    ],
  },
  {
    key: "procurement",
    label: "Procurement",
    icon: ShoppingBag,
    color: "25 75% 50%",
    basePath: "/procurement",
    submodules: [
      { title: "Purchase Orders", url: "/procurement", icon: ShoppingCart },
      { title: "LPO Management", url: "/procurement/lpo", icon: ClipboardCheck },
      { title: "Suppliers", url: "/procurement/suppliers", icon: Truck },
      { title: "Payables", url: "/procurement/payables", icon: SendHorizonal },
      { title: "Aging Analysis", url: "/procurement/aging", icon: BarChart3 },
    ],
  },
  {
    key: "inventory",
    label: "Inventory",
    icon: Package,
    color: "210 40% 50%",
    basePath: "/inventory",
    submodules: [
      { title: "Stock Overview", url: "/inventory", icon: Package },
      { title: "Goods Receipt", url: "/inventory/receipt", icon: PlusCircle },
      { title: "Issuance", url: "/inventory/issue", icon: SendHorizonal },
      { title: "Stock Take", url: "/inventory/stocktake", icon: ClipboardCheck },
      { title: "Movement Report", url: "/inventory/movement", icon: ArrowDownUp },
    ],
  },
  {
    key: "finance",
    label: "Finance Management",
    icon: DollarSign,
    color: "38 92% 50%",
    basePath: "/finance",
    submodules: [
      { title: "Finance Dashboard", url: "/finance", icon: DollarSign },
      { title: "Billing", url: "/finance/billing", icon: CreditCard },
      { title: "Insurance Claims", url: "/finance/insurance", icon: FileSpreadsheet },
      { title: "Accounts Receivable", url: "/finance/accounts-receivable", icon: Receipt },
      { title: "Accounts Payable", url: "/finance/accounts-payable", icon: BadgeDollarSign },
      { title: "General Ledger", url: "/finance/general-ledger", icon: BookOpen },
      { title: "Asset Management", url: "/finance/assets", icon: Building2 },
      { title: "Budget Management", url: "/finance/budget", icon: BarChart3 },
    ],
  },
  {
    key: "accounts-receivable",
    label: "Accounts Receivable",
    icon: Receipt,
    color: "38 70% 45%",
    basePath: "/accounts-receivable",
    submodules: [
      { title: "Invoices", url: "/accounts-receivable", icon: Receipt },
      { title: "Statements", url: "/accounts-receivable/statements", icon: FileSpreadsheet },
      { title: "Allocations", url: "/accounts-receivable/allocations", icon: BadgeDollarSign },
      { title: "Journal Vouchers", url: "/accounts-receivable/journals", icon: BookOpen },
    ],
  },
  {
    key: "general-ledger",
    label: "General Ledger",
    icon: BookOpen,
    color: "210 50% 40%",
    basePath: "/general-ledger",
    submodules: [
      { title: "Chart of Accounts", url: "/general-ledger", icon: BookOpen },
      { title: "Journal Entries", url: "/general-ledger/journals", icon: FileText },
      { title: "Trial Balance", url: "/general-ledger/trial-balance", icon: Calculator },
      { title: "Bank Reconciliation", url: "/general-ledger/bank", icon: Landmark },
      { title: "Inter-Bank Transfers", url: "/general-ledger/transfers", icon: ArrowLeftRight },
    ],
  },
  {
    key: "fixed-assets",
    label: "Fixed Assets",
    icon: Building2,
    color: "210 30% 45%",
    basePath: "/fixed-assets",
    submodules: [
      { title: "Asset Register", url: "/fixed-assets", icon: Building2 },
      { title: "Acquisitions", url: "/fixed-assets/acquisitions", icon: PlusCircle },
      { title: "Depreciation", url: "/fixed-assets/depreciation", icon: TrendingUp },
      { title: "Disposal", url: "/fixed-assets/disposal", icon: Wrench },
    ],
  },
  {
    key: "hr",
    label: "HR & Payroll",
    icon: UserCog,
    color: "270 40% 50%",
    basePath: "/hr",
    submodules: [
      { title: "Staff Directory", url: "/hr", icon: UsersRound },
      { title: "Leave Management", url: "/hr/leave", icon: CalendarDays },
      { title: "Attendance", url: "/hr/attendance", icon: UserCheck },
      { title: "Payroll", url: "/hr/payroll", icon: Banknote },
      { title: "Tax & Benefits", url: "/hr/tax", icon: Calculator },
    ],
  },
  {
    key: "messaging",
    label: "Messaging",
    icon: MessageSquare,
    color: "192 60% 42%",
    basePath: "/messaging",
    submodules: [
      { title: "Inbox", url: "/messaging", icon: Inbox },
      { title: "Compose", url: "/messaging/compose", icon: Send },
      { title: "Broadcasts", url: "/messaging/broadcasts", icon: Mail },
      { title: "Notifications", url: "/messaging/notifications", icon: Bell },
    ],
  },
  {
    key: "ticketing",
    label: "Ticketing System",
    icon: Ticket,
    color: "30 80% 50%",
    basePath: "/ticketing",
    submodules: [
      { title: "All Tickets", url: "/ticketing", icon: ListOrdered },
      { title: "New Ticket", url: "/ticketing/new", icon: PlusCircle },
      { title: "My Tickets", url: "/ticketing/mytickets", icon: Inbox },
      { title: "Statistics", url: "/ticketing/stats", icon: BarChart3 },
    ],
  },
  {
    key: "it",
    label: "IT & Support",
    icon: Server,
    color: "240 35% 45%",
    basePath: "/it",
    submodules: [
      { title: "IT Dashboard", url: "/it", icon: Settings },
      { title: "Helpdesk Tickets", url: "/it/tickets", icon: ClipboardCheck },
      { title: "Hardware Inventory", url: "/it/hardware", icon: Cpu },
      { title: "Software Licenses", url: "/it/software", icon: Server },
      { title: "Access Control", url: "/it/access", icon: Lock },
      { title: "Network Monitoring", url: "/it/network", icon: Wifi },
    ],
  },
  {
    key: "reports",
    label: "Reports",
    icon: FileBarChart,
    color: "152 50% 42%",
    basePath: "/reports",
    submodules: [
      { title: "Financial Reports", url: "/reports", icon: PieChart },
      { title: "Clinical Reports", url: "/reports/clinical", icon: Activity },
      { title: "Inventory Reports", url: "/reports/inventory", icon: Table },
      { title: "Payroll Reports", url: "/reports/payroll", icon: ScrollText },
      { title: "Export", url: "/reports/export", icon: Download },
    ],
  },
  {
    key: "admin",
    label: "Administration",
    icon: Shield,
    color: "0 0% 45%",
    basePath: "/admin",
    submodules: [
      { title: "User Management", url: "/admin", icon: UsersRound },
      { title: "Roles & Permissions", url: "/admin/roles", icon: Lock },
      { title: "Access Control", url: "/admin/access-control", icon: ShieldCheck },
      { title: "Audit Trail", url: "/admin/audit", icon: ScrollText },
      { title: "System Settings", url: "/admin/settings", icon: Settings },
    ],
  },
  {
    key: "super-admin",
    label: "Super Admin",
    icon: Crown,
    color: "45 100% 50%",
    basePath: "/super-admin",
    submodules: [
      { title: "God Mode", url: "/super-admin", icon: Zap },
      { title: "Module Control", url: "/super-admin/modules", icon: Settings },
      { title: "System Health", url: "/super-admin/health", icon: Activity },
      { title: "Emergency Controls", url: "/super-admin/emergency", icon: AlertTriangle },
      { title: "Global Audit", url: "/super-admin/audit", icon: ScrollText },
      { title: "System Override", url: "/super-admin/override", icon: Power },
    ],
  },
];

function addTicketingSubmodule(modules: Module[]): Module[] {
  return modules.map((mod) => {
    if (mod.key === "ticketing") {
      return mod;
    }

    return {
      ...mod,
      submodules: [
        ...mod.submodules,
        {
          title: "Raise IT Ticket",
          url: `/ticketing?module=${encodeURIComponent(mod.label)}`,
          icon: ClipboardCheck,
        },
      ],
    };
  });
}

export const modules = addTicketingSubmodule(baseModules);

export function getModuleByPath(pathname: string): Module | undefined {
  if (pathname === "/" || pathname.startsWith("/dashboard")) {
    return modules.find((m) => m.key === "dashboard");
  }
  return modules.find(
    (m) => m.basePath !== "/" && pathname.startsWith(m.basePath)
  );
}
